# Generated by Django 4.1.7 on 2023-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventplayerdata',
            name='unique_event_player',
        ),
        migrations.RemoveConstraint(
            model_name='matchplayerdata',
            name='unique_match_player',
        ),
        migrations.RemoveConstraint(
            model_name='playerpermissions',
            name='unique_player_permission',
        ),
        migrations.RenameField(
            model_name='apikeys',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='eventplayerdata',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventplayerdata',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='eventplayerstats',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='matchplayerdata',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='matchplayerdata',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='matchteamdata',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='matchteamdata',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='mogitournamentwinners',
            old_name='final_event_id',
            new_name='final_event',
        ),
        migrations.RenameField(
            model_name='mogitournamentwinners',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='discord_id',
            new_name='discord',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='playerpermissions',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='playerpermissions',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='wartournamentwinners',
            old_name='final_match_id',
            new_name='final_match',
        ),
        migrations.RenameField(
            model_name='wartournamentwinners',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.AddConstraint(
            model_name='eventplayerdata',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_event_player'),
        ),
        migrations.AddConstraint(
            model_name='matchplayerdata',
            constraint=models.UniqueConstraint(fields=('player', 'match'), name='unique_match_player'),
        ),
        migrations.AddConstraint(
            model_name='playerpermissions',
            constraint=models.UniqueConstraint(fields=('player', 'permission'), name='unique_player_permission'),
        ),
    ]
